import React from 'react';
import { Link } from 'react-router-dom';
import { Sparkles, Zap, ShieldCheck, Globe, Code2, ArrowRight } from 'lucide-react';

function LandingPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 font-sans selection:bg-indigo-500/30 relative overflow-hidden">
      
      {/* Background decoration */}
      <div className="absolute top-0 inset-x-0 h-96 bg-gradient-to-b from-indigo-500/10 to-transparent pointer-events-none" />
      <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-indigo-600/10 rounded-full blur-[150px] pointer-events-none opacity-40" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-blue-600/10 rounded-full blur-[150px] pointer-events-none opacity-40" />

      {/* Navbar */}
      <nav className="relative z-20 flex items-center justify-between px-6 py-8 max-w-7xl mx-auto">
        <div className="flex items-center gap-2">
          <div className="p-2 rounded-xl bg-indigo-500/10 border border-indigo-500/20">
            <Sparkles className="w-6 h-6 text-indigo-400" />
          </div>
          <span className="text-2xl font-black tracking-tighter text-white">UI2MD</span>
        </div>
        <div className="flex items-center gap-6">
          <Link 
            to="/app" 
            className="px-5 py-2.5 bg-white text-slate-950 rounded-xl font-bold hover:bg-indigo-50 transition-all shadow-xl shadow-white/5 active:scale-95"
          >
            Launch App
          </Link>
        </div>
      </nav>

      {/* Hero Section */}
      <header className="relative z-10 pt-20 pb-32 px-6 max-w-7xl mx-auto text-center">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-xs font-bold tracking-widest uppercase mb-8 animate-in fade-in slide-in-from-bottom-4">
          <Zap size={14} className="fill-indigo-500/50" />
          AI Powered Design Extraction
        </div>
        
        <h1 className="text-5xl md:text-8xl font-black tracking-tight mb-8 leading-[1.1] animate-in fade-in slide-in-from-bottom-6 duration-700">
          Turn Websites into <br />
          <span className="bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 via-white to-blue-400">
            Premium Design Docs
          </span>
        </h1>
        
        <p className="text-lg md:text-xl text-slate-400 max-w-3xl mx-auto mb-12 font-medium leading-relaxed animate-in fade-in slide-in-from-bottom-8 duration-700">
          Extract real computed CSS, typography, and design tokens from any URL. 
          Get a perfectly structured <code>DESIGN.md</code> file generated by AI instantly.
        </p>

        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 animate-in fade-in slide-in-from-bottom-10 duration-700">
          <Link 
            to="/app" 
            className="group flex items-center gap-2 px-8 py-4 bg-indigo-600 hover:bg-indigo-500 text-white rounded-2xl font-bold text-lg transition-all shadow-2xl shadow-indigo-500/25 active:scale-95"
          >
            Get Started Free
            <ArrowRight size={20} className="group-hover:translate-x-1 transition-transform" />
          </Link>
          <a 
            href="https://github.com/Faahad0412/ui2md" 
            target="_blank" 
            className="flex items-center gap-2 px-8 py-4 bg-slate-900/50 hover:bg-slate-800 border border-slate-800 rounded-2xl font-bold text-lg transition-all backdrop-blur-xl"
          >
            <Code2 size={20} />
            View on GitHub
          </a>
        </div>
      </header>

      {/* Features Grid */}
      <section className="relative z-10 py-32 px-6 max-w-7xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          
          <div className="p-8 rounded-3xl bg-slate-900/40 border border-slate-800/50 backdrop-blur-xl hover:border-indigo-500/30 transition-all group">
            <div className="w-12 h-12 rounded-2xl bg-indigo-500/10 flex items-center justify-center mb-6 border border-indigo-500/20 group-hover:bg-indigo-500/20 transition-colors">
              <Globe className="w-6 h-6 text-indigo-400" />
            </div>
            <h3 className="text-xl font-bold mb-4">Any Website</h3>
            <p className="text-slate-400 font-medium leading-relaxed">
              Just paste a URL. Our headless engine scrapes real computed styles directly from the browser.
            </p>
          </div>

          <div className="p-8 rounded-3xl bg-slate-900/40 border border-slate-800/50 backdrop-blur-xl hover:border-indigo-500/30 transition-all group">
            <div className="w-12 h-12 rounded-2xl bg-indigo-500/10 flex items-center justify-center mb-6 border border-indigo-500/20 group-hover:bg-indigo-500/20 transition-colors">
              <Sparkles className="w-6 h-6 text-indigo-400" />
            </div>
            <h3 className="text-xl font-bold mb-4">Gemini AI Engine</h3>
            <p className="text-slate-400 font-medium leading-relaxed">
              Google Gemini 1.5 Flash processes raw data into high-quality, professional markdown documentation.
            </p>
          </div>

          <div className="p-8 rounded-3xl bg-slate-900/40 border border-slate-800/50 backdrop-blur-xl hover:border-indigo-500/30 transition-all group">
            <div className="w-12 h-12 rounded-2xl bg-indigo-500/10 flex items-center justify-center mb-6 border border-indigo-500/20 group-hover:bg-indigo-500/20 transition-colors">
              <ShieldCheck className="w-6 h-6 text-indigo-400" />
            </div>
            <h3 className="text-xl font-bold mb-4">BYOK Model</h3>
            <p className="text-slate-400 font-medium leading-relaxed">
              Bring Your Own Key. Full privacy — your API keys are stored only in your local browser storage.
            </p>
          </div>

        </div>
      </section>

      {/* Footer */}
      <footer className="relative z-10 py-20 px-6 text-center border-t border-slate-900">
        <p className="text-slate-500 font-medium">
          Made with ✨ by <a href="#" className="text-indigo-400 hover:underline">Faahad0412</a>
        </p>
      </footer>

    </div>
  );
}

export default LandingPage;
